{
  description = "Logos Workspace — unified multi-repo development environment";

  # ── Inputs ─────────────────────────────────────────────────────────────────
  #
  # The bulk of this block is auto-generated by `ws sync-graph` from each
  # repo's flake.lock.  Nix's flake parser requires `inputs` to be a literal
  # attrset (no `let`, `//`, `import`, or `builtins.mapAttrs` allowed), so
  # the per-repo follows can't be computed at evaluation time — they must
  # be written into this file directly.
  #
  # To regenerate after editing any repo's flake inputs:
  #
  #     ws sync-graph
  #
  # URL overrides (logos-blockchain org, tutorial sub-flakes) and manual
  # follows overrides live in `scripts/ws` near the top of `cmd_sync_graph`.

  inputs = {
    # ── Manual: shared Nix infrastructure ──────────────────────────────────
    #
    # logos-nix pins the workspace's nixpkgs (and therefore Qt).  Overriding
    # logos-nix here propagates to ALL downstream consumers via the auto-
    # generated follows below.
    # fleet-kit: pinned to the logos-fleet fork at an explicit rev; pin.sh moves the rev
    # to the repos/logos-nix gitlink (this manual input is skipped by `ws sync-graph`).
    logos-nix.url = "github:logos-fleet/logos-nix/1a1ba66071a5d46bf2b33e0f4a9728af65d0035d";
    nixpkgs.follows = "logos-nix/nixpkgs";
    # Pinned explicitly because logos-blockchain-module's upstream lock
    # currently references an invalid commit-ish via /0.2.1.
    logos-blockchain.url = "github:logos-blockchain/logos-blockchain/88941ff33f2e028591b9d0ed2549a328d54f0cfa";

    # BEGIN AUTO-INPUTS — generated by `ws sync-graph`, do not edit by hand
    logos-protocol = {
      url = "github:logos-fleet/logos-protocol/5eb36c19fb5a54d775c5b18843861437651eca86";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-qt-sdk = {
      url = "github:logos-fleet/logos-qt-sdk/a115ecef4e3dbd56dc3dec32c9619f34777353c9";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-plugin-qt.follows = "logos-plugin-qt";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-cpp-sdk = {
      url = "github:logos-fleet/logos-cpp-sdk/51c293ad0a190691cc52135fed4bee5ce75561a5";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-view-module-runtime = {
      url = "github:logos-fleet/logos-view-module-runtime/95be5f93918f4e8e8d3370e5deca458979768cbb";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-design-system.follows = "logos-design-system";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-plugin-qt.follows = "logos-plugin-qt";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-module-client = {
      url = "github:logos-fleet/logos-module-client/19e8e92803be91ae8ef03daf9a1ac86712789dd2";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.logos-qt-sdk.follows = "logos-qt-sdk";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-module = {
      url = "github:logos-fleet/logos-module/3120dd231ab799e9fe8ace4ae8fe008228cb9a41";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package.follows = "logos-package";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-liblogos = {
      url = "github:logos-fleet/logos-liblogos/1abd7eeb0c1153fb242b0474cae30d1a625dc7f4";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-module.follows = "logos-module";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package.follows = "logos-package";
      inputs.logos-package-manager.follows = "logos-package-manager";
      inputs.logos-plugin-qt.follows = "logos-plugin-qt";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.logos-qt-sdk.follows = "logos-qt-sdk";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.process-stats.follows = "process-stats";
    };
    logos-logoscore-cli = {
      url = "github:logos-fleet/logos-logoscore-cli/88d4c45e91151d997b4c84d8c3da1163bcda6362";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-js-sdk.follows = "logos-js-sdk";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package-downloader-module.follows = "logos-package-downloader-module";
      inputs.logos-package-manager.follows = "logos-package-manager";
      inputs.logos-package-manager-module.follows = "logos-package-manager-module";
      inputs.logos-plugin-qt.follows = "logos-plugin-qt";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.logos-test-modules.follows = "logos-test-modules";
      inputs.nix-bundle-appimage.follows = "nix-bundle-appimage";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-capability-module = {
      url = "github:logos-fleet/logos-capability-module/90a3f4688a50794ec744eb77543d49c32e416ec0";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-package = {
      url = "github:logos-fleet/logos-package/723f98952e2ee6a8cfd10a1d287d605a5a484e86";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-plugin-qt = {
      url = "github:logos-fleet/logos-plugin-qt/664a3c0e408ec222d778d6ea5c757acd0bef3b8f";
      inputs.logos-module.follows = "logos-module";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-module-builder = {
      url = "github:logos-fleet/logos-module-builder/35379167b63c27a165dae6ef3071d25ee60f7f9d";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-design-system.follows = "logos-design-system";
      inputs.logos-module.follows = "logos-module";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-plugin-core.follows = "logos-plugin-qt";
      inputs.logos-plugin-qt.follows = "logos-plugin-qt";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.logos-qt-sdk.follows = "logos-qt-sdk";
      inputs.logos-rust-sdk.follows = "logos-rust-sdk";
      inputs.logos-standalone-app.follows = "logos-standalone-app";
      inputs.logos-view-module-runtime.follows = "logos-view-module-runtime";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-bundle-dir = {
      url = "github:logos-fleet/nix-bundle-dir/ffc410b7f2bab32b1c2ceb347c56902e7321049c";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-bundle-lgx = {
      url = "github:logos-fleet/nix-bundle-lgx/237e42f1fcb70f1e77cedb48daf5cba0498e204a";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package.follows = "logos-package";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-bundle-appimage = {
      url = "github:logos-fleet/nix-bundle-appimage/04a3cf89f8ba3dc20f08a8e2b6c337a672bceda7";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-bundle-macos-app = {
      url = "github:logos-fleet/nix-bundle-macos-app/d6b0cc518e599ab7a52258bf3e1f8123c8a01d31";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-standalone-app = {
      url = "github:logos-fleet/logos-standalone-app/1aa90d083c03679de1e2f0291adb818032d044fc";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-design-system.follows = "logos-design-system";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.logos-qt-sdk.follows = "logos-qt-sdk";
      inputs.logos-view-module-runtime.follows = "logos-view-module-runtime";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-basecamp = {
      url = "github:logos-fleet/logos-basecamp/a5369fe913e3341f09a5cb340bca6b51b67bce06";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-chat-module.follows = "logos-chat-module";
      inputs.logos-chat-ui.follows = "logos-chat-ui";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-delivery-module.follows = "logos-delivery-module";
      inputs.logos-design-system.follows = "logos-design-system";
      inputs.logos-evm-eth-rpc-module.follows = "logos-evm-eth-rpc-module";
      inputs.logos-evm-keystore-module.follows = "logos-evm-keystore-module";
      inputs.logos-evm-wallet-ui.follows = "logos-evm-wallet-ui";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-libp2p-module.follows = "logos-libp2p-module";
      inputs.logos-module.follows = "logos-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package.follows = "logos-package";
      inputs.logos-package-downloader-module.follows = "logos-package-downloader-module";
      inputs.logos-package-manager.follows = "logos-package-manager";
      inputs.logos-package-manager-module.follows = "logos-package-manager-module";
      inputs.logos-package-manager-ui.follows = "logos-package-manager-ui";
      inputs.logos-plugin-qt.follows = "logos-plugin-qt";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.logos-qt-sdk.follows = "logos-qt-sdk";
      inputs.logos-view-module-runtime.follows = "logos-view-module-runtime";
      inputs.nix-bundle-appimage.follows = "nix-bundle-appimage";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
      inputs.nix-bundle-macos-app.follows = "nix-bundle-macos-app";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-accounts-module = {
      url = "github:logos-fleet/logos-accounts-module/4fd4cb0be3d281b4a9b3303f892b2b265edb2a62";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-accounts-ui = {
      url = "github:logos-fleet/logos-accounts-ui/324b2c6e0aa76ecbed3a2d2922fd16093539eb25";
      inputs.accounts_module.follows = "logos-accounts-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-chat-module = {
      url = "github:logos-fleet/logos-chat-module/8c896abd42021416df2f6939ed15609063823c4a";
      inputs.logos-delivery-module.follows = "logos-delivery-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-chat-ui = {
      url = "github:logos-fleet/logos-chat-ui/a6990e263679ed2fe0b4e9c11c75b80ccd7cb0a4";
      inputs.chat_module.follows = "logos-chat-module";
      inputs.logos-delivery-module.follows = "logos-delivery-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-package-manager = {
      url = "github:logos-fleet/logos-package-manager/72e7e3a400b140b5950bb6d1b46cbeaa0e2a79b6";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package.follows = "logos-package";
      inputs.nix-bundle-appimage.follows = "nix-bundle-appimage";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-package-downloader = {
      url = "github:logos-fleet/logos-package-downloader/a315e55bcfb5c842611336899c318db87e0812d8";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package.follows = "logos-package";
      inputs.nix-bundle-appimage.follows = "nix-bundle-appimage";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-package-manager-module = {
      url = "github:logos-fleet/logos-package-manager-module/437f98a976d8a6d0c68e8ffb81d714b599678528";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.logos-package-manager.follows = "logos-package-manager";
    };
    logos-package-downloader-module = {
      url = "github:logos-fleet/logos-package-downloader-module/7ff159535898e498b7b68d38226f24290a96f17c";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.logos-package-downloader.follows = "logos-package-downloader";
    };
    logos-package-manager-ui = {
      url = "github:logos-fleet/logos-package-manager-ui/3f93b6a5f44eb79d48e8efd263e6c04e15fb2c14";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.logos-package.follows = "logos-package";
      inputs.package_downloader.follows = "logos-package-downloader-module";
      inputs.package_manager.follows = "logos-package-manager-module";
    };
    logos-storage-module = {
      url = "github:logos-fleet/logos-storage-module/8feb7cc0f7806bc2b25faa884e1bb9076b993969";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-storage-ui = {
      url = "github:logos-fleet/logos-storage-ui/823be657d236afe824b9804d6aee69c14b1d4507";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
      inputs.storage_module.follows = "logos-storage-module";
    };
    logos-wallet-module = {
      url = "github:logos-fleet/logos-wallet-module/f6f9c160410db824531f42dd8b27ccecd39ca589";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-wallet-ui = {
      url = "github:logos-fleet/logos-wallet-ui/26f8f5bebd511e91e29019e1e7c892bd5753439d";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
      inputs.wallet_module.follows = "logos-wallet-module";
    };
    logos-delivery-module = {
      url = "github:logos-fleet/logos-delivery-module/8526f5b1d7b4f9e200ebbf81ec379926debfa651";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
    };
    logos-delivery-demo = {
      url = "github:logos-fleet/logos-delivery-demo/b5fec54843a20290fdc847762bdbc7f2d7217da1";
      inputs.delivery_module.follows = "logos-delivery-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-blockchain-module = {
      url = "github:logos-fleet/logos-blockchain-module/581323e9e587a3b8057f8f63a9ade1ff1892111a";
      inputs.logos-blockchain.follows = "logos-blockchain";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-blockchain-ui = {
      url = "github:logos-fleet/logos-blockchain-ui/eb513b5a79f558f5718a5ca0eafac1d5fda7d832";
      inputs.blockchain_module.follows = "logos-blockchain-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
    };
    logos-execution-zone-wallet-ui = {
      url = "github:logos-fleet/logos-execution-zone-wallet-ui/da1b021db5315eccd1e39835268bbc08633adc12";
      inputs.lez_core.follows = "logos-execution-zone-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
    };
    logos-execution-zone-module = {
      url = "github:logos-fleet/logos-execution-zone-module/033f807a3b1690fb2f8e661cb8067646b8a98242";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
    };
    logos-libp2p-module = {
      url = "github:logos-fleet/logos-libp2p-module/f2fc350c01954ea764343effa5945223609c0593";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.logoscore-cli.follows = "logos-logoscore-cli";
      inputs.package-manager.follows = "logos-package-manager";
      inputs.libp2p.url = "github:vacp2p/nim-libp2p/7c73484cc0c57a5f649dd3d277cef1c7c4de28f0";
    };
    logos-webview-app = {
      url = "github:logos-fleet/logos-webview-app/b5d1bb40da6ba550076069a10cf9beaac45aa515";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
    };
    counter_qml.url = "github:logos-fleet/counter_qml/8029a894f4221f9284efabbedcee7d9d18929777";
    counter = {
      url = "github:logos-fleet/counter/69bbb0c686c43042759bcd2572b0c33c7ff6dbf7";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-design-system = {
      url = "github:logos-fleet/logos-design-system/bb5b017d0d7cdc1574c31f8cb8ed13c3c84272d8";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nix-bundle-appimage.follows = "nix-bundle-appimage";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nix-bundle-macos-app.follows = "nix-bundle-macos-app";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-js-sdk = {
      url = "github:logos-fleet/logos-js-sdk/4547aea4cb6c283a3aea34e26536e1ef4e4bb43e";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-nim-sdk = {
      url = "github:logos-fleet/logos-nim-sdk/df1f21906e661d96f5e4bda172cb9a619292b603";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-rust-sdk.url = "github:logos-fleet/logos-rust-sdk/661d43431f4bd13ab50869e305e1eaba49579e8a";
    logos-logoscore-py = {
      url = "github:logos-fleet/logos-logoscore-py/6e081b2d2fd87a909b958aa8a97be445229acf75";
      inputs.logos-logoscore-cli.follows = "logos-logoscore-cli";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-test-modules.follows = "logos-test-modules";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-test-modules = {
      url = "github:logos-fleet/logos-test-modules/468c010b93d5e172e36e76419a16c147358e9afd";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-logoscore-cli.follows = "logos-logoscore-cli";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-plugin-qt.follows = "logos-plugin-qt";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    process-stats = {
      url = "github:logos-fleet/process-stats/1cf3220bb26c1fd3beef8064b5bea1ee332ca23d";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-module-viewer = {
      url = "github:logos-fleet/logos-module-viewer/b6489c1aab8c1590fa127dbaedb39708f3614fbc";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-package-manager.follows = "logos-package-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-evm-net-proxy.url = "github:logos-fleet/logos-evm-net-proxy/564a730551b677ff8292144c3773a46d99a18b91";
    logos-evm-keystore-module = {
      url = "github:logos-fleet/logos-evm-keystore-module/6ebc37c529f93de1795c71dc186e58603f1961d4";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-evm-eth-rpc-module = {
      url = "github:logos-fleet/logos-evm-eth-rpc-module/bc360375a21541fcb541d3d3c6b71132c3eeb22e";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-evm-token-list-module = {
      url = "github:logos-fleet/logos-evm-token-list-module/25d5d6b2a96987bb2a757a0348c150baeb675e3b";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-evm-uniswap-module = {
      url = "github:logos-fleet/logos-evm-uniswap-module/30350e191662f206aefc9667abba902a5116e059";
      inputs.eth_rpc_module.follows = "logos-evm-eth-rpc-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-evm-railgun-module = {
      url = "github:logos-fleet/logos-evm-railgun-module/d2607eee84f0748667d56268f3d23028416aa7f1";
      inputs.eth_rpc_module.follows = "logos-evm-eth-rpc-module";
      inputs.keystore_module.follows = "logos-evm-keystore-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-evm-wallet-backend-module = {
      url = "github:logos-fleet/logos-evm-wallet-backend-module/eb39db1258b41773618d51c9b327646d7594bbb0";
      inputs.eth_rpc_module.follows = "logos-evm-eth-rpc-module";
      inputs.keystore_module.follows = "logos-evm-keystore-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.token_list_module.follows = "logos-evm-token-list-module";
      inputs.uniswap_module.follows = "logos-evm-uniswap-module";
    };
    logos-evm-wallet-ui = {
      url = "github:logos-fleet/logos-evm-wallet-ui/48e3643c07afb7afbe657214d3d94cca102a648c";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.wallet_backend_module.follows = "logos-evm-wallet-backend-module";
    };
    # END AUTO-INPUTS
  };

  outputs = { self, nixpkgs, ... }@inputs:
    let
      systems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      forAllSystems = fn: nixpkgs.lib.genAttrs systems fn;

      # The mobile pseudo-systems logos-nix keys its cross package sets by. A
      # cross derivation's `system` is its BUILD platform, so these evaluate
      # anywhere; they are separate keys because an iOS host is
      # stdenv.isDarwin and folding them into `systems` would misroute every
      # `if isDarwin` inside the repos. Only `packages` carries them -- there is
      # no devShell, app or check to run ON a phone.
      #
      # This is what lets `ws build <repo> --target <variant>` reach a mobile
      # artifact THROUGH the workspace flake, so --auto-local / --local
      # overrides propagate to it exactly as they do for a desktop build.
      mobileSystems = [ "aarch64-ios" "aarch64-ios-simulator" "aarch64-android" ];
      forAllPackageSystems = fn: nixpkgs.lib.genAttrs (systems ++ mobileSystems) fn;

      depGraph = import ./nix/dep-graph.nix;

      # Every logos flake input we iterate over for packages/apps/checks.
      # Excludes `logos-nix` (it's a nixpkgs pin, not a buildable repo).
      repoInputNames = builtins.attrNames
        (builtins.removeAttrs depGraph [ "logos-nix" ]);

      # Mapping from flake input name → submodule directory name under repos/.
      # Only entries where the names differ need to be listed.
      inputToDirOverrides = {
        "logos-calc-module" = "logos-tutorial/logos-calc-module";
        "logos-calc-ui"     = "logos-tutorial/logos-calc-ui";
        "logos-calc-ui-cpp" = "logos-tutorial/logos-calc-ui-cpp";
      };

      inputToDir = name: inputToDirOverrides.${name} or name;

    in {

      # ── Packages ──────────────────────────────────────────────────────────
      # nix build .#logos-cpp-sdk          → default package
      # nix build .#logos-basecamp          → default package
      # nix build .#logos-basecamp--portable → non-default output
      # nix build .#logos-liblogos--portable
      # nix bundle --bundler .#nix-bundle-lgx .#logos-chat-module--lib
      # All repo package outputs are exposed: default as the repo name,
      # non-default as <repo>--<output>.
      packages = forAllPackageSystems (system:
        let
          # Collect all package outputs from all repos.
          # Each repo's packages are forwarded lazily — the value is not
          # evaluated until someone actually builds it, so broken store
          # paths or missing files won't cause errors at evaluation time.
          allPkgs = builtins.foldl' (acc: name:
            let
              repoPkgs = (inputs.${name}.packages.${system} or {});
              outNames = builtins.attrNames repoPkgs;
            in
            acc // builtins.listToAttrs (map (outName:
              let
                attrName = if outName == "default" then name else "${name}--${outName}";
              in
              { name = attrName; value = repoPkgs.${outName}; }
            ) outNames)
          ) {} repoInputNames;
        in allPkgs
      );

      # ── legacyPackages ────────────────────────────────────────────────────
      # Every repo's own legacyPackages, forwarded under the repo name and
      # keyed by the system that BUILDS. That is what Android needs and
      # `packages` cannot give it: an Android cross derivation's `system` is
      # its build platform, and `packages.aarch64-android` carries the
      # canonical x86_64-linux one, which a Mac refuses with "platform
      # mismatch" even though the closure is identical. A repo publishes the
      # same artifacts under `legacyPackages.<buildSystem>.mobile.<target>`,
      # and `ws build --target android-arm64` resolves through here (see
      # scripts/_mobile-target).
      #
      # Forwarded through the WORKSPACE flake rather than reached in the repo's
      # own, for the same reason `packages` is: --auto-local / --local override
      # inputs of this flake, and a build that went straight at the sub-repo
      # would not see them.
      legacyPackages = forAllSystems (system:
        builtins.listToAttrs (map (name: {
          inherit name;
          value = inputs.${name}.legacyPackages.${system} or { };
        }) repoInputNames));

      # ── Apps ──────────────────────────────────────────────────────────────
      # nix run .#logos-standalone-app -- --plugin ./result/lib/
      # Forwards apps outputs from all repos. Default app exposed as repo name,
      # non-default as <repo>--<output>.
      apps = forAllSystems (system:
        builtins.foldl' (acc: name:
          let
            repoApps = (inputs.${name}.apps.${system} or {});
            outNames = builtins.attrNames repoApps;
          in
          acc // builtins.listToAttrs (map (outName:
            let
              attrName = if outName == "default" then name else "${name}--${outName}";
            in
            { name = attrName; value = repoApps.${outName}; }
          ) outNames)
        ) {} repoInputNames
      );

      # ── Dev Shells ────────────────────────────────────────────────────────
      # nix develop          → workspace shell (ws CLI + common tools)
      # nix develop .#logos-cpp-sdk → that repo's own devShell
      # nix develop          → workspace shell with ws CLI + common tools
      # For sub-repo devShells use: nix develop path:./repos/<repo-name>
      #   or: ws develop <repo-name>
      devShells = forAllSystems (system:
        let
          pkgs = import nixpkgs { inherit system; };
          # Always delegates to the live scripts/ws in the workspace,
          # without needing to rebuild the devshell. Falls back to the
          # flake directory if LOGOS_WORKSPACE_ROOT is not set.
          wsScript = pkgs.writeShellScriptBin "ws" ''
            exec "''${LOGOS_WORKSPACE_ROOT:-${builtins.toString ./.}}/scripts/ws" "$@"
          '';
        in {
          default = import ./nix/devshell.nix { inherit pkgs wsScript; };
        }
      );

      # ── Checks ────────────────────────────────────────────────────────────
      # nix flake check        → run ALL repo checks
      # nix build .#checks.x86_64-linux.logos-cpp-sdk--test
      checks = forAllSystems (system:
        builtins.foldl' (acc: name:
          let
            result = builtins.tryEval (inputs.${name}.checks.${system} or {});
            repoChecks = if result.success then result.value else {};
            prefixed = nixpkgs.lib.mapAttrs'
              (cname: drv: { name = "${name}--${cname}"; value = drv; })
              repoChecks;
          in
          acc // prefixed
        ) {} repoInputNames
      );

      # ── Bundlers ──────────────────────────────────────────────────────────
      # Forwards nix-bundle-lgx bundlers so scripts can use "$WORKSPACE_ROOT"
      # as the --bundler reference.
      bundlers = forAllSystems (system:
        inputs.nix-bundle-lgx.bundlers.${system}
      );

      # ── Lib (for programmatic use) ────────────────────────────────────────
      lib = {
        inherit repoInputNames inputToDir;
        # Dependency graph: input name → { deps, follows, hasTests }
        depGraph = depGraph;
      };
    };
}
